# Generated by Django 5.0.3 on 2026-03-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0001_modelo_v4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
