# Generated by Django 5.0.3 on 2026-03-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_alter_sensor_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='interfaces',
            field=models.JSONField(blank=True, default=list, help_text='Interfaces de rede detectadas pelo sensor Linux'),
        ),
    ]
