# Generated by Django 6.0.2 on 2026-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('mac', models.CharField(blank=True, max_length=17, null=True)),
                ('hostname', models.CharField(blank=True, max_length=120, null=True)),
                ('vendor', models.CharField(blank=True, max_length=120, null=True)),
                ('os', models.CharField(blank=True, max_length=80, null=True)),
                ('tipo', models.CharField(blank=True, max_length=80, null=True)),
                ('icon', models.CharField(blank=True, max_length=60, null=True)),
                ('status', models.CharField(default='offline', max_length=20)),
                ('risk_score', models.IntegerField(default=10)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('custom_name', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cidr', models.CharField(max_length=32)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('found', models.IntegerField(default=0)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
