# Generated by Django 5.0.3 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dispositivos", "0003_device_availability"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scanrun",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AlterField(
            model_name="dispositivo",
            name="mac",
            field=models.CharField(blank=True, db_index=True, max_length=17, null=True),
        ),
    ]
