# Generated by Django 5.0.3 on 2026-03-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0003_alter_configsistema_node_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsistema',
            name='fw_agente_porta',
            field=models.IntegerField(default=8765, help_text='Porta do agente Flask no sensor Linux (padrão 8765)'),
        ),
    ]
