# Generated by Django 5.0.3 on 2026-08-05 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0004_configsistema_fw_agente_porta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsistema',
            name='adguard_mode',
            field=models.CharField(default='mock', help_text='mock no modo demonstração; real no modo operacional.', max_length=16),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='dns_enabled',
            field=models.BooleanField(default=False, help_text='Indica se o provider DNS está habilitado.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='fw_agente_porta',
            field=models.IntegerField(default=8765, help_text='Porta do agente Flask no sensor Linux.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='fw_enabled',
            field=models.BooleanField(default=False, help_text='Indica se o provider Firewall está habilitado.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='ids_enabled',
            field=models.BooleanField(default=False, help_text='Indica se o provider IDS está habilitado.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='modo',
            field=models.CharField(choices=[('demo', 'Modo Demonstração'), ('prod', 'Modo Operacional')], default='demo', help_text='Modo Demonstração: utiliza dados simulados e bloqueia integrações reais. Modo Operacional: permite instalar, conectar e utilizar componentes reais.', max_length=10),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='ping_timeout',
            field=models.IntegerField(default=1000, help_text='Tempo limite do ping, em milissegundos.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='ret_devices',
            field=models.IntegerField(default=30, help_text='Retenção de dispositivos, em dias.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='ret_dns',
            field=models.IntegerField(default=7, help_text='Retenção de eventos DNS, em dias.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='ret_incidents',
            field=models.IntegerField(default=90, help_text='Retenção de incidentes, em dias.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='ret_logs',
            field=models.IntegerField(default=7, help_text='Retenção de logs, em dias.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='scan_interval',
            field=models.IntegerField(default=60, help_text='Intervalo entre varreduras, em segundos.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='session_expiry',
            field=models.IntegerField(default=480, help_text='Tempo de expiração da sessão, em minutos.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='suricata_interval',
            field=models.IntegerField(default=5, help_text='Intervalo de leitura do eve.json, em segundos.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='suricata_min_severity',
            field=models.IntegerField(default=2, help_text='Severidade mínima dos eventos IDS.'),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='suricata_mode',
            field=models.CharField(default='mock', help_text='mock no Modo Demonstração; eve no Modo Operacional quando o Suricata estiver configurado.', max_length=16),
        ),
    ]
