# Generated by MoonShield Appliance

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0008_configsistema_prod_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsistema',
            name='node_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='node_country_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='node_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='node_location_accuracy',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='node_location_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='node_location_source',
            field=models.CharField(choices=[('manual', 'Manual Confirmado'), ('browser', 'Browser Confirmado pelo Usuário'), ('config', 'Configurado'), ('geoip', 'WAN GeoIP'), ('unknown', 'Desconhecido')], default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='node_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='node_region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]

