# Generated by Django 5.0.3 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("configuracoes", "0010_configsistema_mapbox_access_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configsistema",
            name="adguard_mode",
            field=models.CharField(
                default="real",
                help_text="real no modo operacional; o modo global decide quando simular.",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="configsistema",
            name="adguard_url",
            field=models.CharField(blank=True, default="http://127.0.0.1", max_length=255),
        ),
        migrations.AlterField(
            model_name="configsistema",
            name="dns_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o provider DNS/AdGuard Home está habilitado.",
            ),
        ),
    ]
