# Generated by Django 5.0.3 on 2026-08-04 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_sensor_interfaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSuricata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Suricata Local', max_length=100)),
                ('ativo', models.BooleanField(db_index=True, default=True)),
                ('interface_wan', models.CharField(blank=True, max_length=100)),
                ('interface_lan', models.CharField(blank=True, max_length=100)),
                ('interface_mgmt', models.CharField(blank=True, max_length=100)),
                ('interfaces_monitoradas', models.JSONField(blank=True, default=list)),
                ('home_net', models.JSONField(blank=True, default=list)),
                ('dns_interno', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('yaml_path', models.CharField(default='/etc/suricata/suricata.yaml', max_length=500)),
                ('eve_path', models.CharField(default='/var/log/suricata/eve.json', max_length=500)),
                ('cursor_path', models.CharField(default='var/cursors/suricata_eve.cursor', max_length=500)),
                ('modo_captura', models.CharField(choices=[('lan', 'Somente LAN'), ('lan_wan', 'LAN + WAN'), ('personalizado', 'Personalizado')], default='lan_wan', max_length=30)),
                ('instalar_et_open', models.BooleanField(default=True)),
                ('instalar_regras_moonshield', models.BooleanField(default=True)),
                ('reiniciar_servicos', models.BooleanField(default=True)),
                ('suricata_instalado', models.BooleanField(default=False)),
                ('suricata_configurado', models.BooleanField(default=False)),
                ('instalacao_concluida', models.BooleanField(db_index=True, default=False)),
                ('onboarding_concluido', models.BooleanField(db_index=True, default=False)),
                ('versao_suricata', models.CharField(blank=True, max_length=100)),
                ('ultimo_diagnostico', models.JSONField(blank=True, default=dict)),
                ('ultimo_status', models.JSONField(blank=True, default=dict)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Suricata',
                'verbose_name_plural': 'Configurações Suricata',
                'ordering': ['-ativo', '-atualizado_em'],
                'indexes': [models.Index(fields=['ativo'], name='idx_cfg_suricata_ativo'), models.Index(fields=['onboarding_concluido'], name='idx_cfg_suri_onb_ok'), models.Index(fields=['instalacao_concluida'], name='idx_cfg_suri_inst_ok')],
            },
        ),
        migrations.CreateModel(
            name='TarefaSuricata',
            fields=[
                ('id', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('diagnostico', 'Diagnóstico'), ('instalacao', 'Instalação'), ('configuracao', 'Configuração'), ('atualizacao_regras', 'Atualização de regras'), ('validacao', 'Validação'), ('reinicio_suricata', 'Reinício do Suricata'), ('reinicio_monitor', 'Reinício do monitor')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('cancelado', 'Cancelado'), ('ignorado', 'Ignorado')], db_index=True, default='pendente', max_length=20)),
                ('progresso', models.PositiveSmallIntegerField(default=0)),
                ('etapa_atual', models.CharField(blank=True, max_length=100)),
                ('mensagem', models.TextField(blank=True)),
                ('parametros', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('erro', models.TextField(blank=True)),
                ('cancelamento_solicitado', models.BooleanField(db_index=True, default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('configuracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='incidentes.configuracaosuricata')),
            ],
            options={
                'verbose_name': 'Tarefa Suricata',
                'verbose_name_plural': 'Tarefas Suricata',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='LogTarefaSuricata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(default=0)),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('sucesso', 'Sucesso'), ('aviso', 'Aviso'), ('erro', 'Erro'), ('debug', 'Debug')], db_index=True, default='info', max_length=20)),
                ('etapa', models.CharField(blank=True, max_length=100)),
                ('mensagem', models.TextField()),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('tarefa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='incidentes.tarefasuricata')),
            ],
            options={
                'verbose_name': 'Log de tarefa Suricata',
                'verbose_name_plural': 'Logs de tarefas Suricata',
                'ordering': ['sequencia', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='tarefasuricata',
            index=models.Index(fields=['tipo', 'status'], name='idx_tarefa_tipo_status'),
        ),
        migrations.AddIndex(
            model_name='tarefasuricata',
            index=models.Index(fields=['status', 'criado_em'], name='idx_tarefa_status_criado'),
        ),
        migrations.AddIndex(
            model_name='tarefasuricata',
            index=models.Index(fields=['cancelamento_solicitado', 'status'], name='idx_tarefa_cancel_status'),
        ),
        migrations.AddIndex(
            model_name='tarefasuricata',
            index=models.Index(fields=['configuracao', 'criado_em'], name='idx_tarefa_cfg_criado'),
        ),
        migrations.AddIndex(
            model_name='logtarefasuricata',
            index=models.Index(fields=['tarefa', 'sequencia'], name='idx_suricata_log_ts'),
        ),
        migrations.AddIndex(
            model_name='logtarefasuricata',
            index=models.Index(fields=['tarefa', 'criado_em'], name='idx_suricata_log_tc'),
        ),
        migrations.AddIndex(
            model_name='logtarefasuricata',
            index=models.Index(fields=['nivel', 'criado_em'], name='idx_suricata_log_nc'),
        ),
        migrations.AddConstraint(
            model_name='logtarefasuricata',
            constraint=models.UniqueConstraint(fields=('tarefa', 'sequencia'), name='uq_suricata_log_seq'),
        ),
    ]
