# Generated by Django 6.0.2 on 2026-02-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0001 configuracoes initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsistema',
            name='detected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='detected_interfaces',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='configsistema',
            name='detected_sysinfo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='configsistema',
            name='modo',
            field=models.CharField(choices=[('demo', 'Demo / Mock'), ('prod', 'Produção')], default='demo', help_text='Demo: dados simulados. Produção: integrações reais.', max_length=10),
        ),
    ]
