# Generated by Django 5.0.3 on 2026-03-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracoes', '0002_configsistema_detected_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsistema',
            name='node_name',
            field=models.CharField(blank=True, default='MS-NODE-01', max_length=64),
        ),
    ]
