# Generated by Django 5.0.3 on 2026-10-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WifiTrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('mac_address', models.CharField(db_index=True, max_length=17, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('descricao', models.TextField(blank=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'dispositivo Wi-Fi confiÃ¡vel',
                'verbose_name_plural': 'dispositivos Wi-Fi confiÃ¡veis',
                'ordering': ['nome', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WifiAuthorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=150)),
                ('ip_address', models.GenericIPAddressField(db_index=True, protocol='IPv4')),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('authorized_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('auth_source', models.CharField(choices=[('AUTH01', 'AUTH01')], default='AUTH01', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-authorized_at', '-id'],
                'indexes': [models.Index(fields=['active', 'ip_address'], name='wifi_auth_active_ip_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='wifiauthorization',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('mac_address',), name='wifi_one_active_authorization_per_mac'),
        ),
    ]
