# Generated by Django 5.0.3 on 2026-10-09 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wifi_access', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wifitrusteddevice',
            options={'ordering': ['nome', 'id'], 'verbose_name': 'dispositivo Wi-Fi confiável', 'verbose_name_plural': 'dispositivos Wi-Fi confiáveis'},
        ),
    ]
