# Generated by Django

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoDiagnostico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ferramenta', models.CharField(db_index=True, max_length=64)),
                ('alvo', models.TextField()),
                ('opcoes', models.JSONField(default=dict)),
                ('origem', models.CharField(choices=[('quick', 'Quick'), ('guided', 'Guided'), ('terminal', 'Terminal'), ('auto', 'Auto')], default='guided', max_length=32)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('warn', 'Warning'), ('err', 'Error')], db_index=True, max_length=16)),
                ('resumo', models.TextField(blank=True)),
                ('stdout', models.TextField(blank=True)),
                ('stderr', models.TextField(blank=True)),
                ('resultado_estruturado', models.JSONField(blank=True, default=dict)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('contexto_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Execução de Diagnóstico',
                'verbose_name_plural': 'Execuções de Diagnóstico',
                'ordering': ['-created_at'],
            },
        ),
    ]
