# Generated by Django 5.0.3 on 2026-03-18 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidentes', '0002_alter_sensor_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=255)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Allowlist',
                'verbose_name_plural': 'Allowlist',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='BlocklistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(db_index=True, max_length=50)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto'), ('SOC', 'SOC')], default='Manual', max_length=20)),
                ('expires', models.CharField(default='∞', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blocklist',
                'verbose_name_plural': 'Blocklist',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GeoblockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=5, unique=True)),
                ('dir', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('BOTH', 'BOTH')], default='IN', max_length=5)),
                ('enabled', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'GeoBlock',
                'verbose_name_plural': 'GeoBlock',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='NatEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iface', models.CharField(choices=[('WAN', 'WAN'), ('LAN', 'LAN'), ('VPN', 'VPN')], default='WAN', max_length=10)),
                ('wan_port', models.CharField(max_length=10)),
                ('lan_ip', models.GenericIPAddressField()),
                ('lan_port', models.CharField(max_length=10)),
                ('proto', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('any', 'ANY')], default='TCP', max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NAT / Port Forward',
                'verbose_name_plural': 'NAT / Port Forwards',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RegraFirewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('action', models.CharField(choices=[('allow', 'ALLOW'), ('deny', 'DENY')], default='deny', max_length=10)),
                ('iface', models.CharField(choices=[('WAN', 'WAN'), ('LAN', 'LAN'), ('VPN', 'VPN'), ('any', 'ANY')], default='WAN', max_length=10)),
                ('dir', models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=5)),
                ('proto', models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('any', 'ANY')], default='TCP', max_length=10)),
                ('src', models.CharField(default='any', max_length=100)),
                ('dst', models.CharField(default='any', max_length=100)),
                ('port', models.CharField(default='any', max_length=50)),
                ('desc', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('log', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Regra de Firewall',
                'verbose_name_plural': 'Regras de Firewall',
                'ordering': ['priority'],
                'indexes': [models.Index(fields=['enabled', 'priority'], name='idx_fw_rule_ativo_prio')],
            },
        ),
        migrations.CreateModel(
            name='EventoFirewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('acao', models.CharField(choices=[('ALLOW', 'Allow'), ('DROP', 'Drop'), ('DENY', 'Deny'), ('LOG', 'Log')], db_index=True, default='ALLOW', max_length=10)),
                ('chain', models.CharField(blank=True, max_length=20)),
                ('proto', models.CharField(blank=True, max_length=10)),
                ('src_ip', models.GenericIPAddressField(db_index=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('iface', models.CharField(blank=True, db_index=True, max_length=30)),
                ('iface_saida', models.CharField(blank=True, max_length=30)),
                ('tamanho', models.IntegerField(blank=True, null=True)),
                ('ttl', models.IntegerField(blank=True, null=True)),
                ('flags_tcp', models.CharField(blank=True, max_length=50)),
                ('prefixo', models.CharField(blank=True, max_length=20)),
                ('event_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_firewall', to='incidentes.sensor')),
            ],
            options={
                'verbose_name': 'Evento de Firewall',
                'verbose_name_plural': 'Eventos de Firewall',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['src_ip', 'timestamp'], name='idx_fw_srcip_ts'), models.Index(fields=['acao', 'timestamp'], name='idx_fw_acao_ts'), models.Index(fields=['dst_port', 'timestamp'], name='idx_fw_dstport_ts')],
            },
        ),
    ]
