# Generated by Django 5.0.3 on 2026-03-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrafirewall',
            name='pendente',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='regrafirewall',
            name='sincronizada',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='regrafirewall',
            index=models.Index(fields=['pendente', 'sincronizada'], name='idx_fw_rule_sync'),
        ),
    ]
