# Generated by Django 5.0.3 on 2026-03-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0002_regrafirewall_pendente_regrafirewall_sincronizada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='regrafirewall',
            name='deletado',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='regrafirewall',
            name='iface',
            field=models.CharField(default='any', max_length=30),
        ),
        migrations.AddIndex(
            model_name='regrafirewall',
            index=models.Index(fields=['deletado'], name='idx_fw_rule_deletado'),
        ),
    ]
