# Generated by Django 5.0.3 on 2026-08-20 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall', '0003_regrafirewall_deletado_alter_regrafirewall_iface_and_more'),
        ('incidentes', '0004_configuracaosuricata_tarefasuricata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoFirewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(db_index=True, default=False)),
                ('onboarding_concluido', models.BooleanField(default=False)),
                ('instalacao_concluida', models.BooleanField(default=False)),
                ('interface_wan', models.CharField(blank=True, max_length=32)),
                ('interface_lan', models.CharField(blank=True, max_length=32)),
                ('interface_mgmt', models.CharField(blank=True, max_length=32)),
                ('home_net', models.CharField(blank=True, max_length=64)),
                ('nftables_instalado', models.BooleanField(default=False)),
                ('tabela_instalada', models.BooleanField(default=False)),
                ('chains_ok', models.BooleanField(default=False)),
                ('agent_ativo', models.BooleanField(default=False)),
                ('monitor_ativo', models.BooleanField(default=False)),
                ('persistencia_ok', models.BooleanField(default=False)),
                ('operacional', models.BooleanField(db_index=True, default=False)),
                ('nftables_versao', models.CharField(blank=True, max_length=100)),
                ('agent_versao', models.CharField(blank=True, max_length=50)),
                ('ultimo_status', models.JSONField(blank=True, default=dict)),
                ('ultimo_diagnostico', models.JSONField(blank=True, default=dict)),
                ('ultimo_erro', models.TextField(blank=True)),
                ('ultimo_healthcheck_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração do Firewall',
                'verbose_name_plural': 'Configuração do Firewall',
            },
        ),
        migrations.CreateModel(
            name='TarefaFirewall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('instalar', 'Instalar'), ('reparar', 'Reparar'), ('aplicar_regras', 'Aplicar regras'), ('rollback', 'Rollback'), ('diagnosticar', 'Diagnosticar'), ('desinstalar', 'Desinstalar')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('executando', 'Executando'), ('sucesso', 'Sucesso'), ('erro', 'Erro'), ('cancelada', 'Cancelada')], db_index=True, default='pendente', max_length=20)),
                ('progresso', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('etapa_atual', models.CharField(blank=True, max_length=150)),
                ('mensagem', models.CharField(blank=True, max_length=500)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('logs', models.JSONField(blank=True, default=list)),
                ('erro', models.TextField(blank=True)),
                ('snapshot_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.FloatField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tarefa do Firewall',
                'verbose_name_plural': 'Tarefas do Firewall',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='regrafirewall',
            options={'ordering': ['priority', 'id'], 'verbose_name': 'Regra de Firewall', 'verbose_name_plural': 'Regras de Firewall'},
        ),
        migrations.AddField(
            model_name='allowlistentry',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blocklistentry',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='geoblockentry',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='natentry',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='regrafirewall',
            name='sincronizada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regrafirewall',
            name='ultimo_erro',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='allowlistentry',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blocklistentry',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='blocklistentry',
            name='source',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Auto', 'Auto'), ('SOC', 'SOC')], db_index=True, default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='eventofirewall',
            name='chain',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='eventofirewall',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='eventofirewall',
            name='flags_tcp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='eventofirewall',
            name='iface',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='eventofirewall',
            name='iface_saida',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='eventofirewall',
            name='prefixo',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='eventofirewall',
            name='proto',
            field=models.CharField(blank=True, db_index=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='geoblockentry',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='natentry',
            name='enabled',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='natentry',
            name='lan_port',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='natentry',
            name='wan_port',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='regrafirewall',
            name='dir',
            field=models.CharField(choices=[('in', 'IN'), ('out', 'OUT'), ('forward', 'FORWARD')], default='in', max_length=10),
        ),
        migrations.AlterField(
            model_name='regrafirewall',
            name='dst',
            field=models.CharField(default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='regrafirewall',
            name='iface',
            field=models.CharField(choices=[('WAN', 'WAN'), ('LAN', 'LAN'), ('MGMT', 'MGMT'), ('VPN', 'VPN'), ('any', 'ANY')], default='any', max_length=32),
        ),
        migrations.AlterField(
            model_name='regrafirewall',
            name='port',
            field=models.CharField(default='any', max_length=255),
        ),
        migrations.AlterField(
            model_name='regrafirewall',
            name='proto',
            field=models.CharField(choices=[('TCP', 'TCP'), ('UDP', 'UDP'), ('ICMP', 'ICMP'), ('ICMPV6', 'ICMPv6'), ('any', 'ANY')], default='TCP', max_length=10),
        ),
        migrations.AlterField(
            model_name='regrafirewall',
            name='src',
            field=models.CharField(default='any', max_length=255),
        ),
        migrations.AddIndex(
            model_name='blocklistentry',
            index=models.Index(fields=['source', 'criado_em'], name='idx_fw_block_src_dt'),
        ),
        migrations.AddIndex(
            model_name='eventofirewall',
            index=models.Index(fields=['iface', 'timestamp'], name='idx_fw_iface_ts'),
        ),
        migrations.AddIndex(
            model_name='geoblockentry',
            index=models.Index(fields=['enabled', 'dir'], name='idx_fw_geo_enabled_dir'),
        ),
        migrations.AddIndex(
            model_name='natentry',
            index=models.Index(fields=['enabled', 'iface'], name='idx_fw_nat_enabled_if'),
        ),
        migrations.AddIndex(
            model_name='tarefafirewall',
            index=models.Index(fields=['status', 'criado_em'], name='idx_fw_task_status_dt'),
        ),
        migrations.AddIndex(
            model_name='tarefafirewall',
            index=models.Index(fields=['tipo', 'status'], name='idx_fw_task_tipo_status'),
        ),
    ]
