# Generated by Django 5.0.3 on 2026-10-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firewall", "0004_configuracaofirewall_tarefafirewall_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="regrafirewall",
            name="dir",
            field=models.CharField(
                choices=[
                    ("in", "IN"),
                    ("out", "OUT"),
                    ("forward", "FORWARD"),
                    ("both", "AMBOS"),
                ],
                default="in",
                max_length=10,
            ),
        ),
    ]
