# Generated by Django 6.0.2 on 2026-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_userprofile_sidebar_collapsed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completo',
            field=models.BooleanField(default=False),
        ),
    ]
