# Generated by Django 6.0.2 on 2026-02-25 16:34

import autenticacao.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=autenticacao.models.avatar_upload_path)),
                ('display_name', models.CharField(blank=True, max_length=80)),
                ('cargo', models.CharField(blank=True, default='Analista SOC / Redes', max_length=100)),
                ('departamento', models.CharField(blank=True, default='Blue Team · CSIRT', max_length=100)),
                ('ramal', models.CharField(blank=True, max_length=40)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('telefone', models.CharField(blank=True, max_length=30)),
                ('api_key', models.CharField(blank=True, editable=False, max_length=64)),
                ('totp_enabled', models.BooleanField(default=False)),
                ('last_password_change', models.DateTimeField(blank=True, null=True)),
                ('tema', models.CharField(choices=[('dark', 'Escuro'), ('light', 'Claro')], default='dark', max_length=10)),
                ('densidade', models.CharField(choices=[('compacto', 'Compacto'), ('normal', 'Normal'), ('espacoso', 'Espaçoso')], default='normal', max_length=10)),
                ('scan_interval', models.CharField(choices=[('1', '1 min'), ('2', '2 min'), ('5', '5 min'), ('0', 'Manual')], default='5', max_length=5)),
                ('auto_scan', models.BooleanField(default=True)),
                ('notificacoes', models.BooleanField(default=True)),
                ('som_alerta', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil do Usuário',
                'verbose_name_plural': 'Perfis dos Usuários',
            },
        ),
    ]
