# Generated by Django 5.0.3 on 2026-08-22 18:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoRoteamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ipv4_forward', models.BooleanField(default=False, help_text='Habilita net.ipv4.ip_forward.')),
                ('gerenciamento_automatico_rota_default', models.BooleanField(default=True, help_text='Permite ao MoonShield gerenciar a rota padrão através da WAN principal.')),
                ('rollback_automatico', models.BooleanField(default=True)),
                ('tempo_confirmacao', models.PositiveSmallIntegerField(default=60, help_text='Tempo em segundos para confirmar uma alteração antes do rollback automático.', validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(600)])),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Configuração de roteamento',
                'verbose_name_plural': 'Configurações de roteamento',
            },
        ),
        migrations.CreateModel(
            name='InterfaceRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(db_index=True, help_text='Nome real da interface no Linux. Ex: enp0s3.', max_length=64, unique=True)),
                ('descricao', models.CharField(blank=True, default='', help_text='Descrição amigável opcional.', max_length=120)),
                ('mac_address', models.CharField(blank=True, default='', help_text='Último MAC address detectado pelo Agent.', max_length=32)),
                ('papel', models.CharField(choices=[('unassigned', 'Não atribuída'), ('wan', 'WAN'), ('lan', 'LAN'), ('mgmt', 'Gerenciamento'), ('dmz', 'DMZ'), ('custom', 'Personalizada')], db_index=True, default='unassigned', max_length=20)),
                ('principal', models.BooleanField(default=False, help_text='Define a interface principal daquele papel. Ex: WAN principal ou LAN principal.')),
                ('habilitada', models.BooleanField(default=True)),
                ('acesso_gerenciamento', models.BooleanField(default=False, help_text='Permite que esta interface seja utilizada para acesso administrativo ao MoonShield.')),
                ('ipv4_modo', models.CharField(choices=[('dhcp', 'DHCP'), ('static', 'Estático'), ('disabled', 'Desativado')], default='dhcp', max_length=16)),
                ('ipv4_endereco', models.GenericIPAddressField(blank=True, help_text='IPv4 estático desejado. Deve permanecer vazio quando ipv4_modo=DHCP.', null=True, protocol='IPv4')),
                ('ipv4_prefixo', models.PositiveSmallIntegerField(blank=True, help_text='Prefixo IPv4. Ex: 24.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('gateway', models.GenericIPAddressField(blank=True, help_text='Gateway desejado para esta interface.', null=True, protocol='IPv4')),
                ('rota_padrao', models.BooleanField(default=False, help_text='Indica se esta interface deve fornecer rota default.')),
                ('metrica', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4294967295)])),
                ('mtu', models.PositiveIntegerField(default=1500, validators=[django.core.validators.MinValueValidator(576), django.core.validators.MaxValueValidator(65535)])),
                ('backend', models.CharField(choices=[('unknown', 'Desconhecido'), ('networkmanager', 'NetworkManager'), ('networkd', 'systemd-networkd'), ('ifupdown', 'ifupdown'), ('runtime', 'Runtime / iproute2')], default='unknown', max_length=24)),
                ('conexao_nome', models.CharField(blank=True, default='', help_text='Nome do profile/conexão do NetworkManager.', max_length=160)),
                ('conexao_uuid', models.CharField(blank=True, default='', help_text='UUID do profile NetworkManager, quando disponível.', max_length=64)),
                ('estado_link', models.CharField(choices=[('unknown', 'Desconhecido'), ('up', 'UP'), ('down', 'DOWN')], default='unknown', max_length=16)),
                ('carrier', models.BooleanField(blank=True, help_text='Estado físico do link quando detectável.', null=True)),
                ('ipv4_atual', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('prefixo_atual', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(32)])),
                ('gateway_atual', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('metrica_atual', models.PositiveIntegerField(blank=True, null=True)),
                ('mtu_atual', models.PositiveIntegerField(blank=True, null=True)),
                ('sincronizada', models.BooleanField(db_index=True, default=False)),
                ('pendente', models.BooleanField(db_index=True, default=False)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('detectada_em', models.DateTimeField(blank=True, db_index=True, help_text='Última vez que o Agent confirmou esta interface.', null=True)),
                ('aplicada_em', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Interface de rede',
                'verbose_name_plural': 'Interfaces de rede',
                'ordering': ['papel', '-principal', 'nome'],
                'indexes': [models.Index(fields=['papel', 'principal'], name='rede_iface_papel_princ_idx'), models.Index(fields=['sincronizada', 'pendente'], name='rede_iface_sync_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegraNat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(default='NAT LAN → WAN', max_length=120)),
                ('tipo', models.CharField(choices=[('masquerade', 'Masquerade')], default='masquerade', max_length=20)),
                ('origem_cidr', models.CharField(blank=True, default='', help_text='Opcional. Se vazio, o Agent poderá utilizar a rede da interface de origem.', max_length=64)),
                ('ativa', models.BooleanField(default=True)),
                ('prioridade', models.PositiveIntegerField(default=100)),
                ('sincronizada', models.BooleanField(default=False)),
                ('pendente', models.BooleanField(default=True)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('aplicada_em', models.DateTimeField(blank=True, null=True)),
                ('interface_origem', models.ForeignKey(help_text='Normalmente uma interface LAN.', on_delete=django.db.models.deletion.PROTECT, related_name='regras_nat_origem', to='rede.interfacerede')),
                ('interface_saida', models.ForeignKey(help_text='Normalmente a WAN.', on_delete=django.db.models.deletion.PROTECT, related_name='regras_nat_saida', to='rede.interfacerede')),
            ],
            options={
                'verbose_name': 'Regra NAT',
                'verbose_name_plural': 'Regras NAT',
                'ordering': ['prioridade', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RotaEstatica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(blank=True, default='', max_length=120)),
                ('destino', models.CharField(help_text='Rede destino em CIDR. Ex: 10.20.0.0/16.', max_length=64)),
                ('gateway', models.GenericIPAddressField(blank=True, null=True, protocol='IPv4')),
                ('metrica', models.PositiveIntegerField(default=100)),
                ('ativa', models.BooleanField(default=True)),
                ('sincronizada', models.BooleanField(default=False)),
                ('pendente', models.BooleanField(default=True)),
                ('ultimo_erro', models.TextField(blank=True, default='')),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rotas_estaticas', to='rede.interfacerede')),
            ],
            options={
                'verbose_name': 'Rota estática',
                'verbose_name_plural': 'Rotas estáticas',
                'ordering': ['metrica', 'destino'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotRede',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origem', models.CharField(default='moonshield-agent', max_length=64)),
                ('backend', models.CharField(blank=True, default='', max_length=32)),
                ('dados', models.JSONField(default=dict)),
                ('automatico', models.BooleanField(default=True)),
                ('valido', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots_rede_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Snapshot de rede',
                'verbose_name_plural': 'Snapshots de rede',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AlteracaoRede',
            fields=[
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('interface', 'Interface'), ('routing', 'Roteamento'), ('nat', 'NAT'), ('route', 'Rota'), ('general', 'Configuração geral')], db_index=True, default='general', max_length=24)),
                ('status', models.CharField(choices=[('created', 'Criada'), ('validating', 'Validando'), ('applying', 'Aplicando'), ('waiting_confirmation', 'Aguardando confirmação'), ('confirmed', 'Confirmada'), ('rollback', 'Rollback em andamento'), ('reverted', 'Revertida'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], db_index=True, default='created', max_length=32)),
                ('titulo', models.CharField(blank=True, default='', max_length=160)),
                ('descricao', models.TextField(blank=True, default='')),
                ('configuracao_solicitada', models.JSONField(default=dict, help_text='Payload solicitado pelo Django.')),
                ('resultado_agent', models.JSONField(blank=True, default=dict, help_text='Último resultado estruturado retornado pelo Agent.')),
                ('requer_confirmacao', models.BooleanField(default=True)),
                ('expira_em', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('iniciada_em', models.DateTimeField(blank=True, null=True)),
                ('aplicada_em', models.DateTimeField(blank=True, null=True)),
                ('confirmada_em', models.DateTimeField(blank=True, null=True)),
                ('rollback_em', models.DateTimeField(blank=True, null=True)),
                ('finalizada_em', models.DateTimeField(blank=True, null=True)),
                ('erro', models.TextField(blank=True, default='')),
                ('log', models.TextField(blank=True, default='')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_rede_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_rede_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('snapshot_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_origem', to='rede.snapshotrede')),
                ('snapshot_posterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alteracoes_resultado', to='rede.snapshotrede')),
            ],
            options={
                'verbose_name': 'Alteração de rede',
                'verbose_name_plural': 'Alterações de rede',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='EventoRede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('nivel', models.CharField(choices=[('info', 'Informação'), ('success', 'Sucesso'), ('warning', 'Aviso'), ('error', 'Erro')], db_index=True, default='info', max_length=16)),
                ('codigo', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('titulo', models.CharField(max_length=180)),
                ('mensagem', models.TextField(blank=True, default='')),
                ('dados', models.JSONField(blank=True, default=dict)),
                ('alteracao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='rede.alteracaorede')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_rede', to=settings.AUTH_USER_MODEL)),
                ('interface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='rede.interfacerede')),
            ],
            options={
                'verbose_name': 'Evento de rede',
                'verbose_name_plural': 'Eventos de rede',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['nivel', '-criado_em'], name='rede_event_nivel_data_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='regranat',
            constraint=models.UniqueConstraint(fields=('interface_origem', 'interface_saida', 'tipo'), name='rede_nat_interface_unica'),
        ),
        migrations.AddConstraint(
            model_name='rotaestatica',
            constraint=models.UniqueConstraint(fields=('destino', 'gateway', 'interface', 'metrica'), name='rede_rota_unica'),
        ),
        migrations.AddIndex(
            model_name='alteracaorede',
            index=models.Index(fields=['status', '-criado_em'], name='rede_alt_status_data_idx'),
        ),
        migrations.AddIndex(
            model_name='alteracaorede',
            index=models.Index(fields=['tipo', '-criado_em'], name='rede_alt_tipo_data_idx'),
        ),
    ]
