# Generated by Django 5.0.3 on 2026-09-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rede", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interfacerede",
            name="enderecos_ipv4",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Todos os endereços IPv4 observados pelo Agent.",
            ),
        ),
        migrations.AddField(
            model_name="interfacerede",
            name="estado_sincronizacao",
            field=models.CharField(
                choices=[
                    ("unmanaged", "unmanaged"),
                    ("synced", "synced"),
                    ("pending_apply", "pending_apply"),
                    ("applying", "applying"),
                    ("waiting_confirmation", "waiting_confirmation"),
                    ("drifted", "drifted"),
                    ("missing", "missing"),
                    ("error", "error"),
                ],
                db_index=True,
                default="unmanaged",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="interfacerede",
            name="revisao_aplicada",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="interfacerede",
            name="revisao_desejada",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
